name: Build frontend

on:
    push:
        branches:
            - "*"
    schedule:
        - cron: "39 12 * * 6"

permissions:
    contents: write

jobs:
    run-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - uses: denoland/setup-deno@v2
              with:
                  deno-version: lts
            - name: Run tests
              run: deno test --unstable --allow-read --allow-env --allow-import

    run-linter:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - uses: denoland/setup-deno@v2
              with:
                  deno-version: lts
            - name: Run linter
              run: deno lint

    deploy-to-deno-deploy:
        runs-on: ubuntu-latest
        needs: [run-tests, run-linter]
        permissions:
            id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
            contents: read
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - uses: denoland/setup-deno@v2
              with:
                  deno-version: lts

            - name: Upload to Deno Deploy
              if: github.ref == 'refs/heads/main'
              uses: denoland/deployctl@v1
              with:
                  project: "can-i-use-embed"
                  entrypoint: "main.ts"
                  root: "."
