name: Build frontend

on:
    push:
        branches:
            - "main"
    schedule:
        - cron: "39 12 * * 6"

env:
    DENO_VERSION: v2.4.1

jobs:
    generate-wiki-pages:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Checkout wiki repository
              uses: actions/checkout@v4
              with:
                  repository: ${{github.repository}}.wiki
                  path: wiki

            - uses: denoland/setup-deno@v2
              with:
                  deno-version: ${{ env.DENO_VERSION }}

            - name: Build files
              run: deno run --allow-write --allow-import feature-list-generator/main.ts

            - name: Move generated file
              run: mv FeatureList.md wiki/FeatureList.md

            - name: Push to wiki
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add FeatureList.md
                  git diff-index --quiet HEAD || git commit -m "Add changes" && git push
