name: Build documentation

on:
    push:
        branches:
            - "main"
    schedule:
        - cron: "39 12 * * 6"

env:
    DENO_VERSION: v2.4.1

jobs:
    generate-docs:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - uses: denoland/setup-deno@v2
              with:
                  deno-version: ${{ env.DENO_VERSION }}

            - name: Build documentation
              run: deno run --allow-read --allow-write --allow-import feature-list-generator/main.ts

            - name: Commit and push documentation
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add feature-list-generator/FeatureList.md
                  if ! git diff-index --quiet HEAD; then
                    git commit -m "Update feature list documentation [skip ci]"
                    git push
                  else
                    echo "No changes to commit"
                  fi
